Add metrics middleware
middyjs/middy pull request #619
Opened 2021-02-21 16:53 UTC by fredericbarthelet

What does this implement/fix? Explain your changes.
---------------------------------------------------
Implements #618 

Where has this been tested?
---------------------------
**Node.js Versions:** 14

**Middy Versions:** 1.5.2

**AWS SDK Versions:** No relevant

Todo list
---------

[ x ] Feature/Fix fully implemented
[ x ] Added tests
[ x ] Updated relevant documentation
[ x ] Updated relevant examples

2021-02-21 19:24 UTC, willfarrell commented
I like it, I think this would be a great addition. Not 100% sold on the name yet. What do you think of `cloudwatch-metrics`? It feels long, but `metrics` feels too generic. @lmammino have any opinions on the name?

Would you be able to update this for merging into `release/2.x`? I'd like to avoid new additions to v1.x at this point.

Skimming through it's npm docs is `setProperty("RequestId", handler.path.to.RequestId)` required? Or is it set by default and this if for overriding?

2021-02-23 08:37 UTC, lmammino commented
I like `cloudwatch-metrics`. Before looking at the code, I was actually thinking that this middleware was providing generic hooks to send metrics to an arbitrary backend like statsd.

2021-02-23 19:50 UTC, fredericbarthelet commented
Thanks @willfarrell and @lmammino :)
I implemented your feedbacks :
- rebase on release/2.x 
- rename to `cloudwatch-metrics`

> Skimming through it's npm docs is setProperty("RequestId", handler.path.to.RequestId) required? Or is it set by default and this if for overriding?

`setProperty`, like `putMetric`, are part of the API available on the new `context.metrics` property. This method allows adding context specific property that you'd like to see on you Cloudwatch Insights console. There are no defaults for it, unlike namespace  and dimensions.

For exemple, in a lambda processing payment, you could use `setProperty("Total VAT", 89)` in case you'd like to have this metric available. Maybe my exemple (taken directly from the libs documentation) is not that much clear  ?

2021-02-23 20:06 UTC, willfarrell requested changes

2021-02-23 20:06 UTC, willfarrell commented on packages/cloudwatch-metrics/package.json
> +  },
Can you remove devDependencies, they are not needed in v2

2021-02-23 20:06 UTC, willfarrell commented on packages/cloudwatch-metrics/package.json
> +    "aws-embedded-metrics": "^2.0.4"
Can we lock the version ` "aws-embedded-metrics": "2.0.4"`.

2021-02-24 15:37 UTC, willfarrell approved these changes

2021-02-24 15:40 UTC, willfarrell commented
@fredericbarthelet can you commit the `package-lock.json` as well please. It's required for the tests.

2021-02-25 08:30 UTC, fredericbarthelet commented
@willfarrell `package-lock.json` added :)
I noticed all package-lock uses `lockfileVersion: 1` except root package-lock, using v2 (from npm 7). Is this expected ? Should I target v1 or v2 for my lock file ?

https://github.com/middyjs/middy/blob/b75acc929df0f4f1bc75b99d6b9404b83b1e30af/package-lock.json#L4

2021-02-26 04:40 UTC, willfarrell commented
The lockfileVersion change is unexpected but good to know. My local must have finally updated causing the change. Can you update to use v1. The CI uses npm v6.

2021-03-02 08:28 UTC, fredericbarthelet commented
@willfarrell, I added a commit to change main `package-lock.json` file back to lockFileVersion 1 :)

2021-03-02 17:44 UTC, willfarrell commented
Thanks, looks like it's still failing on other lockfile v2's. I pushed a fix for these. One last rebase should do the trick, then we can merge in. Thank you for your patience on resolving this lockfile version issue. We have another PR that will properly bump all to lockfile v2 in the works.

2021-03-04 12:43 UTC, fredericbarthelet commented
@willfarrell I just rebased, everything's green now :)

2021-03-04 17:51 UTC, merged

2021-03-04 17:51 UTC, willfarrell commented
Great! I'm just waiting on another PR before minting a new version. Hope that's okay.

2021-03-04 20:10 UTC, fredericbarthelet commented
Thanks @willfarrell :) No problem waiting a bit more for v2 ;)

2022-01-13 19:28 UTC, willfarrell commented
@fredericbarthelet With AWS powertools released (https://github.com/awslabs/aws-lambda-powertools-typescript/tree/main/packages/metrics). Is their implementation better/easier to use than this middleware?

2022-01-18 11:09 UTC, fredericbarthelet commented
Hi @willfarrell, ultimately the powertool implementation is more complete and will be the prevailing implementation. However, in its current state, the powertool remains a beta-only, not to be used in production solution. I'd wait out of beta before deprecating the metrics middleware. Once they're out of beta, I'd be happy to update documentation with a migration path for the new solution.

2022-01-18 16:46 UTC, willfarrell commented
Perfect, I was thinking the same but wanted to make sure I got your feedback as you championed this middleware. I've added to the v4 list to revisit then, unless power tools hits production ready before v3 is released.